Repository caarlos0/helm-charts, pull requests merged in 2021-08, with the labels that each got.

#24 feat: bump prometheus-operator chart
  charts/thanos/Chart.yaml
  charts/thanos/requirements.lock
  charts/thanos/requirements.yaml
Labels: size/S

#25 feat: kubelet metrics path
  charts/thanos/Chart.yaml
  charts/thanos/values.yaml
Labels: size/XS

#26 fix: kubelet values
  charts/thanos/Chart.yaml
  charts/thanos/values.yaml
Labels: size/XS

#27 feat: use prometheus-stack and upgrade prometheus image to latest ver…
  charts/thanos/Chart.yaml
  charts/thanos/README.md
  charts/thanos/hack/test.sh
  charts/thanos/requirements.lock
  charts/thanos/requirements.yaml
  charts/thanos/values.yaml
  values.yaml.example
Labels: size/M

#29 fix: make deps
  Makefile
Labels: size/XS

#28 fix: prometheus-stack
  README.md
  charts/thanos/README.md
  charts/thanos/examples/values1.yaml
  charts/thanos/examples/values2.yaml
  charts/thanos/examples/values3.yaml
  charts/thanos/templates/sidecar-ingress-grpc.yaml
  charts/thanos/templates/sidecar-service-grpc.yaml
Labels: size/S

#30 fix: kube-prometheus-stack name
  README.md
  charts/thanos/README.md
  charts/thanos/examples/values1.yaml
  charts/thanos/examples/values2.yaml
  charts/thanos/examples/values3.yaml
  charts/thanos/templates/sidecar-ingress-grpc.yaml
  charts/thanos/templates/sidecar-service-grpc.yaml
  charts/thanos/values.yaml
  values.yaml.example
Labels: size/S
